### ISSUE TITLE
select_related checked in django 1.8

### ISSUE THREAD

**Issue by jgrisell** [llazzaro/django-scheduler#112]
Hello,

i just installed django 1.8 and I have the error below. Not sure why but it seems to come from line 89
Event.objects.select_related('occurrence').get(pk=self.pk)
of the file schedule/models/events.py

select_related are now checked according to https://docs.djangoproject.com/en/1.8/releases/1.8/

Any way of fixing this ? 
Thank you very much 

params = self.as_sql()
  File "/backoffice/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 367, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/backoffice/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 48, in pre_sql_setup
    self.setup_query()
  File "/backoffice/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 39, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/backoffice/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 203, in get_select
    related_klass_infos = self.get_related_selections(select)
  File "/backoffice/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 743, in get_related_selections
    ', '.join(_get_field_choices()) or '(none)',
FieldError: Invalid field name(s) given in select_related: 'occurrence'. Choices are: creator, rule, calendar,

**Comment by llazzaro** [comment]
The only thing I know is that the relation is on the other side and for some reason django 1.8 fails with select_related.

the line that fails makes some test fails in django 1.8 (not yet supported).

For the record, the line that fails is a performance improvement. I can remove it but it will impact on performance.

I will check django 1.8 changes (if possible) to see why this fails.

**Comment by akaariai** [comment]
Each event can have multiple occurences, but select_related works only for single valued relations. Maybe prefetch_related would work here?

**Comment by nwaxiomatic** [comment]
How does one remove it for now? I can deal with the performance while in development.

**Comment by llazzaro** [comment]
this is the line
https://github.com/llazzaro/django-scheduler/blob/master/schedule/models/events.py#L89

test are failing with django 1.8

**Comment by llazzaro** [comment]
removed optimization since it breaks with django 1.8.

**Comment by llazzaro** [comment]
version is now 0.7.5
