### ISSUE TITLE
REQUEST - View Classes

### ISSUE THREAD

**Issue by nwaxiomatic** [llazzaro/django-scheduler#117]
Is there any reason to avoid rewriting all views as classes?

Views as functions is quite outdated and makes it quite difficult to subclass or modify anything outside of changing the actual scheduler code.

**Comment by llazzaro** [comment]
the code of django-scheduler is very old and when it was written Class based views didn't exist (I think)

**Comment by nwaxiomatic** [comment]
I already rewrote half of them as class-based, I could do a pull request later today.

I did this so that it would be easier to have modal event editing, should I also add that?

**Comment by nwaxiomatic** [comment]
or perhaps just a popup window

**Comment by jdufresne** [comment]
This looks like it was resolved in commit 4662959adbd1ba8ab82eba7584bd8382c39f3228. Perhaps this can be closed.

**Comment by llazzaro** [comment]
thanks. closing this issue
