### ISSUE TITLE
FullCalendar support enhancement and documentation

### ISSUE THREAD

**Issue by nwaxiomatic** [llazzaro/django-scheduler#119]
I am probably going to add this as the main calendar wrapper/viewer
http://fullcalendar.io/
is this a feature that might be wanted in general?
will keep updated on progress

**Comment by nwaxiomatic** [comment]
I also want to add either modal or popup windows for event editing

**Comment by rouxxx** [comment]
Integrating FullCalendar would be great ! Also pop-up/modal window for editing.
Any date in mind ?

**Comment by nwaxiomatic** [comment]
probably late next week, I might do it as a separate set of views because of the bootstrap compatibility.

not sure if people would be mad about needing bootstrap

**Comment by rouxxx** [comment]
Great ! One question (I should open a new thread but you talked about views :p) : is that possible to display the calendar inside the admin ?

**Comment by llazzaro** [comment]
please check this view for fullcalendar https://github.com/llazzaro/django-scheduler/blob/master/schedule/views.py#L338

I added that view to have some fullcalendar support

**Comment by llazzaro** [comment]
here is the ticket https://github.com/llazzaro/django-scheduler/issues/26

probably current fullcalendar support is not documented or incomplete?

**Comment by nwaxiomatic** [comment]
ah! I was wondering what that view was for. there should definitely be some documentation on the matter.

**Comment by llazzaro** [comment]
The docs were never updated! I will try to do it

**Comment by rouxxx** [comment]
Thanks for the answers.

One more question: what are the current limitations of the FullCalendar integration ?

@nwaxiomatic i'm looking forward to see the results ;)

**Comment by nwaxiomatic** [comment]
I've been a bit behind on the rest of my site, so either end of this week or early next week. Its sort of the last thing I'll be working on...

**Comment by rouxxx** [comment]
@nwaxiomatic any news ? no hassle, just to know to evaluate the amount of work of my next weeks ;)

**Comment by nwaxiomatic** [comment]
@rouxxx Hey so I worked on it a bit but had some serious issues and decided to put it off a bit longer. Here is what I found:

I tried incorporating django-fm which I had successfully used for adding modal popups to the base scheduler template fine and dandy.

However, whenever using django-fm on top of FullCalendar, it renders the modals behind the calendar making it quite useless. Not sure where to go from here...

Let me know if you get anything else

**Comment by nwaxiomatic** [comment]
Not looking forward to rewriting an entire ajax popup app

**Comment by rouxxx** [comment]
@nwaxiomatic I'll see what I can do. Would you be available if I need some help ? it would be great.

**Comment by nwaxiomatic** [comment]
Hey @rouxxx we should plan on a time to meet and discuss how to go through it.

Do you use gitter?

**Comment by rouxxx** [comment]
@nwaxiomatic not until now but I can start ;)

Let me know when you are free

**Comment by nwaxiomatic** [comment]
@rouxxx Lets meet tomorrow at 12 EST.
message me at nicholasdwoodward@gmail.com before then

**Comment by llazzaro** [comment]
after you meet I will delete some comments. please use gitter from here https://gitter.im/llazzaro/django-scheduler?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by nwaxiomatic** [comment]
I basically have this working, but Gut for Windows is breaking and I can't get a pull request made :(

**Comment by llazzaro** [comment]
can you paste in gitter the git error?

**Comment by nwaxiomatic** [comment]
I sent a pull request
