### ISSUE TITLE
Is argparse still needed?

### ISSUE THREAD

**Issue by mail6543210** [llazzaro/django-scheduler#124]
Since this app requires `Django>=1.7` in `setup.py`, and `Django>=1.7` drops the support of `Python<2.7`, and `Python>=2.7` has `argparse` as a stdlib, do we still need `argparse`?

If yes, could it be upgrade to newer version?
(that is, unpinned to `argparse==1.1`, or pinned to `argparse>=1.1`)

**Comment by llazzaro** [comment]
I couldn't find any reference. removing this dep.
