### ISSUE TITLE
Static Files: CSS and jQuery

### ISSUE THREAD

**Issue by NylonPython** [llazzaro/django-scheduler#127]
Please put your static CSS and images into the repo. I'm not sure why you don't have it?

**Comment by llazzaro** [comment]
We are going to start using django-bower for jQuery. 
And we are going to start using bootstrap.
Most of the people uses scheduler for the model and not for the templates.

if you want old images, css and js please use this site_media directory https://github.com/llazzaro/django-scheduler-sample/tree/master/project_sample/site_media

I hope to have some free time next weeks to merge some pull requests and update the legacy templates!

**Comment by NylonPython** [comment]
By updating the legacy templates, do you mean actually using a table to display the schedule? That would make life a lot easier for people using the bootstrap responsive tables.

Also, do you know a way to make a view that will display all the calendars that are in the database? I'm trying to make a group scheduling app for study rooms at my university and I am able to get all the calendars to display with a weekly view, but I haven't been able to find a way to load each calendar's event_list. I was thinking about making the event_list into a tuple or a dictionary to store each calendar's data but when I use a dict I get an error about the charset not being correct, even though the periods variable is a dictionary as well and the compiler doesn't have a problem with it.

**Comment by llazzaro** [comment]
done.
please read the new instruction at Readme or here http://django-bower.readthedocs.org/en/latest/installation.html

after adding djangobower to your settings, execute python mange.py bower install and it will install bootstrap and jquery.

scheduler base template will generate status jQuery.js and bootstrap.css status urls to djangobower ones.
