### ISSUE TITLE
edit and delete icons on bootstrap event view

### ISSUE THREAD

**Issue by nwaxiomatic** [llazzaro/django-scheduler#131]
the edit and delete buttons arent working on the new bootstrap edit and they have the same icon.

**Comment by llazzaro** [comment]
will review this soon

**Comment by nwaxiomatic** [comment]
fixed this in recent pr

**Comment by llazzaro** [comment]
thank you!! I will review the pr soon

**Comment by jdufresne** [comment]
PR was merged.
