### ISSUE TITLE
Stopping Duplicate Events/Occurences?

### ISSUE THREAD

**Issue by lawhorkl** [llazzaro/django-scheduler#137]
When you create an occurrence with the same start time and the same end time, the application does not check for other events where there might be a conflict with groups reserving certain times.

My main problem is obviously trying to detect these cases and I was thinking maybe using the Periods within the model some how to check?

psuedocode:

    #create period using parameters of occurrence/event -- Do not save yet
    #before saving to database, compare created period against list of all events/occurrences within the calendar in question
    #if no duplicates/conflicts arise, save to database. Otherwise return an error for conflicting events.

I realize that this isn't the place for troubleshooting/support but this seems to be the only place you can ask these things. All I'd like to know is if I'm on the right track or whether I should go back to the drawing board and think of a new way to try and make this happen.

**Comment by nwaxiomatic** [comment]
I'm working on a an update that will allow you to check event containment and intersection, keep posted.

**Comment by NylonPython** [comment]
Any update on this?

**Comment by nsomaru** [comment]
bump, any update on this? I'd like to help out as I need this functionality

**Comment by nwaxiomatic** [comment]
I really have no idea what would be the best algorithmic way to deal with this... I spent some time trying to figure out what would work best, but couldn't really decide.

Possibilities:
Number each occurrence sequentially, update sequence ids when event changes and then only make new occurrences where there are sequence ids missing?
