### ISSUE TITLE
Event rrules do not properly work

### ISSUE THREAD

**Issue by nwaxiomatic** [llazzaro/django-scheduler#141]
I have a fix that I will push, but basically given this case:

Start: Saturday August 15
End Recur: Tuesday September 15 2015
Rule: Weekly, bymonthday:29,30

The event will recur on both Saturday September 29 and Sunday September 30

This is an issue with rrule, or something, but I made a function that checks for these issues and corrects.

**Comment by llazzaro** [comment]
can you add an unit test for that case?

**Comment by nwaxiomatic** [comment]
there is also an issue with events where the rules, etc make the event non-existent. I also corrected for that.

I am working on writing some functionality to test whether an event is contained in another event. This is useful for the case when you have "availability" events and you want to see if a possible event resides in that availability.

I'll add a test for the final pull request.

**Comment by gabn88** [comment]
Any news on this?

**Comment by nwaxiomatic** [comment]
Never got around to writing tests, but you can check out the original pull request for the algorithm

**Comment by nwaxiomatic** [comment]
I guess I never pushed those either, oops. 

I can post the code later today

**Comment by gabn88** [comment]
That would be great. I'm just getting to know this module as my last resort to get my customers recurring events without end date wish implemented in a properly fashion

**Comment by nwaxiomatic** [comment]
https://github.com/nwaxiomatic/brownstonetutors/blob/master/Schedule/models/events.py

**Comment by gabn88** [comment]
Great! I will check it out!

**Comment by gabn88** [comment]
If I understand it correctly, your way to integrate this app was to copy the necessary bits and build of you own Scheduler app of it? I was thinking about doing it the same way.

**Comment by nwaxiomatic** [comment]
You definitely will need to build another app that references this app.
Only use the schedule app for the base time things.

**Comment by nwaxiomatic** [comment]
fixed in recent pr
