### ISSUE TITLE
Is django-bower a 'hard' dependency?

### ISSUE THREAD

**Issue by techdragon** [llazzaro/django-scheduler#151]
It seems like django-bower is being used to ensure that a current version of otherwise 'normal' jquery and bootstrap are available in order to have something to base the JS and CSS of the calendar UI on. 

Django-Bower is an easy way to ensure you have a 'non python dependency' sorted out ... but instead of it being just a recommendation in the install documentation, after the requirement for Jquery & Bootstrap is explained, to a new developer, its currently in the package dependencies. ;l. 

Can we 'decouple' things a bit here? I was looking forward to using this project before discovering this detail. I already have my static files sorted, with django-compressor, SASS, django-storages, etc...

So if I've already dealt with adding jQuery & Bootstrap myself, do I actually need this?
If so, perhaps it doesn't need to be an install dependency? I'd be happy to write some documentation improvements to help explain the 'two paths' if it was removed from the package dependencies.

**Comment by llazzaro** [comment]
I think you are right.
however, should scheduler ship jQuery and bootstrap ?

**Comment by techdragon** [comment]
I think it was a very good idea to not bundle jQuery and Bootstrap in your own code, its one less thing you have to keep up to date when working on the code. Both of them are very stable libraries that shouldn't be problematic for anyone to obtain.

Since Bootstrap and jQuery both have dozens of public CDN mirrors that encourage you to use their already hosted versions, the simplest way to deal with it would be to have a 'Tutorial Mode' step in the getting started docs. 

Maybe have a heading that reads something like this 

> Django-Scheduler relies on jQuery and Bootstrap to provide its user interface. If you don't need help with adding these to your Django project, you can [skip the next step](#) where we will show you how to add them to your Django project.

Then you have room to explain how to do it 'manually' and could even suggest they go learn how to use django-compressor and/or django-bower if they want to continue learning about static asset handling in django. On the flip side, anyone that wants to not read that info because they know they already have jQuery and Bootstrap and just want to skip ahead to the Django-Scheduler specific stuff, can do so easily and hopefully without confusion.
