### ISSUE TITLE
'schedule/templates' has references to media that doesn't exist

### ISSUE THREAD

**Issue by smcoll** [llazzaro/django-scheduler#16]
There are multiple ways this could be resolved:

1. move 'schedule/templates' to 'project_sample' for demo purposes only, forcing users to handle their own templates
2. include a 'schedule/static' directory with the necessary files
3. make 'schedule/templates' a bit more generic and not depending on any particular media

i personally prefer a combination of #1 and #3: move 'schedule/templates' to 'project_sample/templates/schedule' and then create barebones templates for 'schedule/templates' that require no media.  Also, include any necessary media in 'project_sample/site_media'.

How does that sound?

**Comment by llazzaro** [comment]
we are using django-bower now
