### ISSUE TITLE
Django 1.9 release

### ISSUE THREAD

**Issue by Visgean** [llazzaro/django-scheduler#174]
Tests are working for the 1.9 version but the released version is very old so it does not support it. 

```
from django.contrib.contenttypes import generic
ImportError: cannot import name generic

```

**Comment by llazzaro** [comment]
Hi,

I'm planning to release on pypi by the end of April.

However you can install with pip using this command:

pip install git+https://github.com/llazzaro/django-scheduler.git

**Comment by jdufresne** [comment]
Hi @llazzaro, just curious, why wait until April? Is there existing work to finish before this can be released? If so, are the remaining TODO items documented somewhere? Is there some other concern?

**Comment by llazzaro** [comment]
@jdufresne I will like to release it now but I didn't have time to test the latest code in develop branch.

**Comment by Braintelligence** [comment]
Ok so we have may now. Is the code Django 1.9 compatible?

**Comment by llazzaro** [comment]
have anyone tested master or develop branch? I didn't have time to test it.
After checking if the branch is ok I will release the version on pypi.

**Comment by jdufresne** [comment]
Which branch should we be testing against exactly, master or develop? Which branch will be the next release?

**Comment by llazzaro** [comment]
develop. I just fixed unit tests with a refactor on occ generator (infinite loop).

**Comment by llazzaro** [comment]
done I sent 0.8.0 to pypi!

If someone finds a bug on 0.8.0 I will update to 0.8.1.

I fixed some quick bugs that I found today.
