### ISSUE TITLE
Default template code must be altered as some HTML tags are escaped

### ISSUE THREAD

**Issue by john924xps** [llazzaro/django-scheduler#181]
In a lot of the calendar templates, the following template tag is invoked to display arrows for the next/previous calendar view:

`{% prevnext "tri_month_calendar" calendar periods.month "F Y"%}`

However, although this works on a local server, bring this online will result in the HTML tags of the function `prevnext` to be escaped (at least for Heroku, which I used). Thus, the HTML code will appear as raw HTML on the webpage.

To fix this, the `autoescape` and `endautoescape`, can be added to avoid escaping the HTML tags, like so:
`{% autoescape off %}{% prevnext "tri_month_calendar" calendar periods.month "F Y"%}{% endautoescape %}`

**Comment by llazzaro** [comment]
I will try to avoid using autoescape off and see if there is other way to solve the issue.

**Comment by nordbit** [comment]
https://docs.djangoproject.com/en/1.9/howto/custom-template-tags/#filters-and-auto-escaping
