### ISSUE TITLE
Recurring events spanning daylight savings changes don't display properly

### ISSUE THREAD

**Issue by nwaxiomatic** [llazzaro/django-scheduler#193]
I'm having a hard time pinning this issue down, but when using timezones, if you create a recurring event which spans over a daylight savings change the system will show the wrong time for the occurrences generated. Example:

Event(start = 12pm March 6th, end = 1pm March 6th, rule = weekly, end_recurring = March 14th)

Occurrences show up in the admin as:
occurrence_1 = Occurrence(start = 12pm March 6th, end = 1pm March 6th)
occurrence_2 = Occurrence(start = 1pm March 6th, end = 2pm March 6th)

Because this is the default viewer for Django, it leads me to believe the issue will have to be programmed into the occurrence generation, rather than the viewing of events. This will be a huge headache because every time you check the time of the occurrence with respect to the event, you will have to see if the event spans a daylight savings change for the server and then add/subtract an hour. -_-

**Comment by nwaxiomatic** [comment]
Also I am using "America/New York" as my timezone, if that helps.

**Comment by llazzaro** [comment]
closing as duplicate.

**Comment by mpaolino** [comment]
@nwaxiomatic please check #109 and the recommendation made to the ticket author and let me know if this solves your issue.
