### ISSUE TITLE
example.

### ISSUE THREAD

**Issue by sophianachiba** [llazzaro/django-scheduler#198]
Hello,

I'm looking at the test code in order to use the package on the backend.
let's say I want to create a recurring event and I want it weekly and every Tuesday and Wednesday.
How would you do that?

Thanks!

**Comment by llazzaro** [comment]
Here is an example of scheduler usage https://github.com/llazzaro/django-scheduler-sample
However we need to improve documentation to answer your question.
take a look into the models.py of this project and also on the test_events.py

**Comment by jayfk** [comment]
> take a look into the models.py of this project and also on the test_events.py

I can't seem to find them in the linked project.

**Comment by llazzaro** [comment]
sorry, take a look to models.py and test_events.py in this project not on the sample.
use the sample to know how to use it.
we need people to write docs!
thanks!
