### ISSUE TITLE
Recurrent event uses end - start difference as length

### ISSUE THREAD

**Issue by llazzaro** [llazzaro/django-scheduler#2]
if you want to use recurrent event the difference end - start is used and this is confuse to use for first comers.

**Comment by mpaolino** [comment]
@llazzaro I see that in the code but from an users perspective I'm not sure what you meant.

**Comment by llazzaro** [comment]
@mpaolino the user is the programmer in this case.
 When I was using scheduler a lot, I was planing to do a new model for recurrent events since using the end - start.
I think I will close this one, I don't want to touch the model anymore.

**Comment by mpaolino** [comment]
Like yourself, I don't like the models nor most of the logic underneath but this concept should now be more easy to grasp. Do you think the small changes on #271 should close this? Refactored  "difference" for "duration" which implies time, changed a bit the logic on the event model and added much needed comments.
