### ISSUE TITLE
rule params

### ISSUE THREAD

**Issue by sophianachiba** [llazzaro/django-scheduler#204]
Hello,

is there any documentation on how to input rrule params?
I'm doing it directly from django admin view.

**Comment by sophianachiba** [comment]
I have figured it out.
If you want to have a rule for occurs every wednesday you would do.
For the field rule.params: byweekday:2

Any additional parameters need a ";"
rule.params: byweekday:2;count:3

**Comment by llazzaro** [comment]
thanks for giving the answer, this will be used in docs
