### ISSUE TITLE
occurence order

### ISSUE THREAD

**Issue by sophianachiba** [llazzaro/django-scheduler#205]
Hello,

when doing a event.get_occurrences, is this supposed to return an ordered list?
In my case the last element is the earliest occurence, this is the output I get.

Occurrence: May 22, 2016 to May 23, 2016, 
Occurrence: May 29, 2016 to May 30, 2016, 
Occurrence: June 5, 2016 to June 6, 2016, 
Occurrence: June 12, 2016 to June 13, 2016, 
Occurrence: June 19, 2016 to June 20, 2016, 
Occurrence: June 26, 2016 to June 27, 2016, 
Occurrence: July 3, 2016 to July 4, 2016, 
Occurrence: July 10,2016 to July 11, 2016, 
Occurrence: July 17, 2016 to July 18, 2016, 
Occurrence: July 24, 2016 to July 25, 2016, 
 Occurrence: July 31, 2016 to Aug. 1, 2016, 
 Occurrence: Aug. 7, 2016 to Aug. 8, 2016, 
 Occurrence: Aug. 14, 2016 to Aug. 15, 2016, 
 Occurrence: Aug. 21, 2016 to Aug. 22, 2016, 
 Occurrence: May 15, 2016 to May 16, 2016

**Comment by llazzaro** [comment]
get_occurrences returns a list.
the order of the results could be a bug in the code!

**Comment by llazzaro** [comment]
@sophianachiba I tried to reproduce this issue with the test -> 8872280, however I wasn't able to do it.
could you give us more information or update out test?
here is the test I wrote:

```python
    def test_get_occurrences_is_sorted(self):
        rule = Rule(frequency="DAILY")
        rule.save()
        cal = Calendar(name="MyCal")
        cal.save()
        recurring_data = {
            'title': 'Recent Event',
            'start': datetime.datetime(2016, 1, 5, 8, 0, tzinfo=pytz.utc),
            'end': datetime.datetime(2016, 1, 5, 9, 0, tzinfo=pytz.utc),
            'end_recurring_period': datetime.datetime(2016, 8, 5, 0, 0, tzinfo=pytz.utc),
            'rule': rule,
            'calendar': cal
        }
        recurring_event = Event.objects.create(**recurring_data)

        start = datetime.datetime(2016, 1, 12, 0, 0, tzinfo=pytz.utc)
        end = datetime.datetime(2016, 1, 27, 0, 0, tzinfo=pytz.utc)
        occurrences = recurring_event.get_occurrences(start=start, end=end)

        sorted_occurrences = sorted(occurrences, key=lambda occ: occ.start)

        self.assertEquals(occurrences, sorted_occurrences)
```

**Comment by sophianachiba** [comment]
I will need to find the example again.
I'll get back to you once I run into the problem again.

**Comment by llazzaro** [comment]
check https://github.com/llazzaro/django-scheduler/pull/271
