### ISSUE TITLE
FullCalendar: Missing static file: schedule/css/modal.css

### ISSUE THREAD

**Issue by jdqx** [llazzaro/django-scheduler#221]
@nwaxiomatic @llazzaro 

schedule/templates/schedule/fullcalendar.html line 8 calls for 'schedule/css/modal.css' which does not exist in the develop repo or nwaxiomatic's fork. I tried installing django-fm and using its modal.css, but this does not work because the missing modal.css had been customized.

**Comment by nwaxiomatic** [comment]
Hmm, let me update my local fork. I have made a lot of changes with the modals and I don't think they need any special css anymore.

**Comment by nwaxiomatic** [comment]
Try updating the fullcalendar templates from here, also try updating the schedule.views file (keep a backup). Let me know if you run into any issues, I'd like to merge in my updates. Again, I use this in conjunction with another really customized app and I try to keep the code separate, but I def make some mistakes there sometimes.

https://github.com/nwaxiomatic/django-scheduler/tree/master/schedule

**Comment by jdqx** [comment]
Tested the new templates and views. Before, everything worked except for the modals, but now there are problems at redirectToCreateEvent() in fullcalendar_script.html. The calendar slug used for eventCreateURL is hard coded to your site, so I changed it to match my setup. Still, redirectToCreateEvent() is not producing any URL parameters. This may be triggering the js error: "fullcalendar.js:8564 Uncaught TypeError: spec.class is not a constructor". 

Since we're not using modal.css anymore, let's go ahead and remove the import from <head>.

I'll work with you on this until we get it right. You may want to try spinning up a new virtualenv to isolate this project from other code. Let me know if you need any help.

**Comment by llazzaro** [comment]
thanks for the bug report I will review this

**Comment by nwaxiomatic** [comment]
Hey just a heads up, I finally got to looking at this code as I am having the same issues for the admin view version. I'll let you know when I find the problem.

**Comment by nwaxiomatic** [comment]
The issue arises from 
```
var y = ifNotTempVar('{{ year }}');
var m = ifNotTempVar('{{ month }}');
var d = ifNotTempVar('{{ day }}');
var view = ifNotTempVar('{{ fcview }}', 'month');
```

Are the url patterns you have updated properly? Are you passing in a year, month, day and view type into the template? This should be done from the kwargs in the updated fullcalendar view.

Let me know!

**Comment by nwaxiomatic** [comment]
OK, so the issue is that python and javascript don't get along. The view is literally passing in "None" for null to javascript so we need to add a second catch for that when getting the initial variables
```
function ifNotTempVar(tempVar, other){
        return (tempVar.length == 0 || tempVar == 'None') ? other : tempVar;
    }
```
