### ISSUE TITLE
get_occurrences() returning occurrence before start datetime

### ISSUE THREAD

**Issue by rodxavier** [llazzaro/django-scheduler#226]
I have an event `23 July 2016 00:00:00 to 23 July 2016 23:59:59` and it has a daily recurrence rule with param `byweekday:5,6` which I think should represent Saturdays and Sundays.

Now, when I call `event.get_occurences(start, end)` with start `25 July 2016 00:00:00` and end `01 August 2016 00:00:00`. The method returns a list of three occurrences.

[<Occurrence: July 30, 2016 to July 30, 2016>, <Occurrence: July 31, 2016 to July 31, 2016>, <Occurrence: July 24, 2016 to July 24, 2016>]

**Comment by mpaolino** [comment]
This should be addressed by https://github.com/llazzaro/django-scheduler/pull/271
