### ISSUE TITLE
Recurring Events - Miscalculated Time Blocks 

### ISSUE THREAD

**Issue by TySol** [llazzaro/django-scheduler#233]
- Recurring events won't load into the time slots they are supposed to occupy 
- Often it skips time slots leaving holes in an event's time block, and usually doesn't begin on the intended start time. 
- Experienced when any rrules are being applied, i.e: Daily, Weekly, Monthly, Yearly
- Bug displays in Calendar_day.html

Pictured example: This weekly-recurring event is supposed to start at 8:00 and go until 11:30, but instead starts at 11:00 and goes until 15:00, with holes at 12:00 and 13:30

![scheduler recurring bug](https://cloud.githubusercontent.com/assets/3915961/17531936/5f0ee9ea-5e3b-11e6-9ba5-2015e4606b33.png)

I've been extending this app for a few months now to learn more about Django, and after making significant progress in other areas this issue still has me stumped. The last few days I've rolled back my schedule app to the clean Development branch to see if it was something I caused but I'm still experiencing the issue. Any information that can point me in the right direction to fix this is much appreciated!

**Comment by TySol** [comment]
I haven't yet pinpointed what is going wrong here, but the issue seems to be affecting the reccuring occurences as well: 
<a href="https://github.com/llazzaro/django-scheduler/issues/231">#231: recurring events with multiple "byweekday"s return wrong occurences</a>

And as mentioned in previous issues, I've tried inputting params to match the weekday, i.e: byweekday:2

<a href="https://github.com/llazzaro/django-scheduler/issues/204">#204: rule params</a>

<a href="https://github.com/llazzaro/django-scheduler/issues/229">#229: document dateutil's rule's interval parameter</a>

**Comment by llazzaro** [comment]
ok let me know if you find the issue. an unit test could be very helpful for this case.

In the past I was going to do a heavy refactor on the models since are very difficult to use.

**Comment by mpaolino** [comment]
This should be solved by https://github.com/llazzaro/django-scheduler/pull/271
