### ISSUE TITLE
pip-installed "schedule" app "base.html" template loads before a user's

### ISSUE THREAD

**Issue by jheasly** [llazzaro/django-scheduler#234]
When you pip install `schedule` it creates a working `/templates/base.html` that will load prior to any Django app `templates/base.html` and may cause a user confusion (esp. a newbie). May want to add a warning in the docs.

**Comment by llazzaro** [comment]
Sorry this project is "django-scheduler". To install this project read the README.md (pip install django-scheduler) the project schedule a different one and is maintained by other people https://github.com/dbader/schedule

**Comment by jheasly** [comment]
Right, your project is `django-scheduler`, but 'schedule' (and not `django-scheduler`) is what you add to your `INSTALLED_APPS` — that's what I'm talking about.

In any event, it doesn't change the fact that the app creates a `base.html` template that gets found by Django ahead of any user app templates, possibly creating confusion for an inexperienced Django developer.

**Comment by llazzaro** [comment]
Ok I will see how to change that and don't affect old users. However adding the warning could be helpful.

thanks.

**Comment by llazzaro** [comment]
commit 3145c30 deletes the base template. I don't think someone is using the base.html of the scheduler project.
