### ISSUE TITLE
Unable to show a few hours long event with a rule on daily calendar

### ISSUE THREAD

**Issue by okrutny** [llazzaro/django-scheduler#235]
I would like to specify an event which results in occurences between hours 16-21, everyday.

specifing Event.start to 16:00 and Event.end to 21:00 with "daily" frequency rule doesn't work. Only occurrences between 15:30 and 16 show up.

http://i.stack.imgur.com/wthgJ.png

the _get_occurrence_list on Event model get's called with half hour intervals.

**Comment by TySol** [comment]
As mentioned in <a href="https://github.com/llazzaro/django-scheduler/issues/233">issue 233</a>, there is currently a bug with the recurring rules ("rrules"), and is unresolved

**Comment by okrutny** [comment]
Thank you a lot! Are you willing to write this unit test? :>

**Comment by mpaolino** [comment]
This should be addressed by https://github.com/llazzaro/django-scheduler/pull/271
