### ISSUE TITLE
Static File folder missing

### ISSUE THREAD

**Issue by RaphaelGeode** [llazzaro/django-scheduler#258]
Hi, after an install of your module, I see that static schedule files aren't in its own folder.
And JS file are missing.

**Comment by llazzaro** [comment]
Could you specify which files? did you follow that bower steps on the README?
I think that the JS deps needs to be improved.
Scheduler can't provide a jquery or bootstrap version since it could clash with your project libs.

**Comment by RaphaelGeode** [comment]
fullcalendar.js are missing in schedule/static

**Comment by llazzaro** [comment]
ok merged into develop. Will be released under 0.8.2

**Comment by llazzaro** [comment]
for anyone having issues please see how it was fixed in the example.
Django scheduler uses django-bower to install js library deps.
We don't want to ship jquery or bootstrap to avoid clashing with your own js libs.
