### ISSUE TITLE
Use bootstrap-calendar

### ISSUE THREAD

**Issue by llazzaro** [llazzaro/django-scheduler#26]
we should use this for calendar UI https://github.com/Serhioromano/bootstrap-calendar

**Comment by amitasthana** [comment]
@llazzaro What happened about the rest api?

**Comment by llazzaro** [comment]
I don't have time to do it. The project is open for pull requests. 
Right now I'm only fixing bugs and reviewing pull requests.
I'm looking to add a rest api using django-restful
