### ISSUE TITLE
TypeError on "byweekday:0" Rule param

### ISSUE THREAD

**Issue by rhblind** [llazzaro/django-scheduler#262]
Hi, I'm getting TypeError on [events.py, Line 341](https://github.com/llazzaro/django-scheduler/blob/develop/schedule/models/events.py#L341) when using a Rule with a single argument, ie. `byweekday:0`. The method is trying to iterate an integer, because the `Rule.get_params()` method is not returning a list of values if there's a single argument.

I've got a fix ready which will make `Rule.get_params()` to always return a list of values, regardless of number of arguments.

I'll submit a PR soon.

**Comment by mpaolino** [comment]
This is fixed in #272
