### ISSUE TITLE
How to edit particular occurrence of an event from ui

### ISSUE THREAD

**Issue by sushovan23** [llazzaro/django-scheduler#274]
Hello,
I'm using the openduty project from github which extensively uses django-scheduler for all the events/calendar. I want to understand how to edit particular instance of an event.
Right now I make an event as:
```    
    form = EventForm(data=data or None, instance=instance, initial=initial_data)
    group = Groups.objects.get(id = group_id)
    users = group.users.all()
    if form.is_valid():
        event = form.save(commit=False)
        if instance is None:
            event.creator = request.user
            event.calendar = calendar
        event.save()
```

In UI, there is a javascript function openDetail in html where I'm displaying the calendar view using the scheduletags month_table as below

``` 
function openDetail(node){
      var eventId = node.getAttribute("href").split("_")[1];
      var editUrl = "/events/edit/{{calendar.slug}}/".concat(eventId);
      var destroyUrl = "/events/destroy/{{calendar.slug}}/".concat(eventId);
      var btns = { "Close":function(){$(this).dialog("destroy");}, "Edit":function(){window.location=editUrl;}, "Destroy":function(){window.location=destroyUrl;}};
      dia = $("#edit_dialog").dialog({'buttons':btns, 'modal':true});
      dia = $($(node).attr("href")).dialog({'buttons':btns, 'modal':true, 'title':'Details'});
      dia.dialog('open');
      return false;
    }

//html template code for displaying calendar
{% month_table calendar periods.month "regular" %}
```
I have my methods to edit events or destroy events but I want the ability to edit a single occurrence of event rather than complete series of event. I can look to add a new button to openDetail dialog for edit occurrence but what do I pass to it? Is there any input which you can give me to achieve this as it would really help me out. Right now when I create events I don't see any entries in the occurrence tables that I believe will be generated only when it's needed to be persisted.
Looking forward to getting some insights from you on how to achieve this.

**Comment by sushovan23** [comment]
This issue can be closed. It was misunderstanding in my part to create the event with correct recurrence rule. now I'm able to edit particular occurrence from the daily calendar view.

**Comment by MichaelAchterberg** [comment]
I have the same problem with not being able to create an occurrence in order to edit a single incidence of the recurring event. How do I create the correct recurrence rule or create a link to create and edit single incidence of the event?
