### ISSUE TITLE
byweekday param

### ISSUE THREAD

**Issue by iV1n5** [llazzaro/django-scheduler#29]
Hi, it looks like you don't support the byweekday params. From the dateutil doc you can read:

_byweekday: [...]  It's also possible to use an argument n for the weekday instances, which will mean the nth occurrence of this weekday in the period. For example, with MONTHLY, or with YEARLY and BYMONTH, using FR(+1) in byweekday will specify the first friday of the month where the recurrence happens._

This means that I can use byweekday:1, but not byweekday:MO(1)

Some things can be done using the bysetpos param, but not all of them. Am I wrong? 

Why did you choose not to support it?

Thanks!

**Comment by mpaolino** [comment]
Fixed on #272

**Comment by sinanthottan** [comment]
@mpaolino  I am trying for multiple days in a week. 
frequency = "WEEKLY", name = "Every TH and SAT", params='BYDAY=3,5;BYSETPOS=-1
This is not working out. I am newbie, can you please guide me to create a recurring event which occurs Weekly every Thursday & Saturday.

Thanks in advance
