### ISSUE TITLE
How to import the FullCalendar into a parent view/template?

### ISSUE THREAD

**Issue by jdqx** [llazzaro/django-scheduler#314]
How to import the FullCalendar into a parent view/template? I shrunk down the size of FullCalendar drastically so that it will fit inside of a sidebar. The parent view is not class-based nor does it use mixins.

**Comment by mikekeda** [comment]
@jdqx  If you want just show a calendar you can do it with js, check https://fullcalendar.io

It's easy to connect js with django-scheduler:
```
$('#calendar').fullCalendar({
    events: '/schedule/api/occurrences?calendar_slug=myslug'
});
```

**Comment by jdufresne** [comment]
This was answered. Closing.
