### ISSUE TITLE
Plural verbose name

### ISSUE THREAD

**Issue by i5ar** [llazzaro/django-scheduler#327]
Is there any reason for the singular name calendar as `verbose_name_plural` in [calendars.py](https://github.com/llazzaro/django-scheduler/blob/develop/schedule/models/calendars.py#L150)?

    class Meta(object):
        ...
        verbose_name_plural = _('calendar')

Since we can create more than one calendar, can we change it to the plural?

**Comment by llazzaro** [comment]
The line was modified 8 years ago. I think is a typo.
