### ISSUE TITLE
Why is color_event not nullable in the last update?

### ISSUE THREAD

**Issue by BakanovKirill** [llazzaro/django-scheduler#329]

**Comment by llazzaro** [comment]
It's a bad practice to have null values. https://docs.djangoproject.com/en/1.11/ref/models/fields/#null
Probably we need to add a default value.

**Comment by BakanovKirill** [comment]
You screwed lots of people databases, so i need to add a whitespace or something like this for color and description... Seems like not a DRY solution.

**Comment by llazzaro** [comment]
@BakanovKirill please be respecful. I do this for free. If you don't like the project fork it or use another one.
I approved the change but it was not made by me.
Please try to change your way of working and test new versions before using them.
I hope not to see this type of comments anymore.

**Comment by llazzaro** [comment]
add reference to commit 74baa0543aaf793c8902105e5c0
