### ISSUE TITLE
How do I store the list of attendees with an Occurence?

### ISSUE THREAD

**Issue by WingedDoom** [llazzaro/django-scheduler#330]
![2017-07-05 11 09 30](https://user-images.githubusercontent.com/6613809/27855327-c23ca03a-6172-11e7-8ac3-59db690b1b88.png)
I need to store a list of attendees with some of the occurences I got in the calendar. But I have no Idea how to do that. I wanted to make a new Attendees model which would have properties with Occurence and User, but I'm not sure if the desired occurence is persisted in the db or not.

**Comment by junctionapps** [comment]
@WingedDoom - did you figure this out? I'm asking myself the same question for minutes of each meeting. Do I create a Minutes model with a foreign key field to Occurrence, or do I create a model "Minutes(Occurrence):" and use it when saving the occurrence? Or do you create a CustomOccurrence(Occurrence): which you could store the minutes in and also use as a Foreign Key an an Attendee model (or many to many field depending on your circumstance).

**Comment by lggwettmann** [comment]
I use a model Attendees with foreign keys to User and Occurrence. When creating a new Attendee, I save the occurrence to make sure it's persisted. That also means that in this case every occurrence with an attendee is persisted.

**Comment by lggwettmann** [comment]
Seems this thread can be closed. :) @llazzaro

**Comment by jdufresne** [comment]
> Seems this thread can be closed

Thanks.
