### ISSUE TITLE
Bower Components Folder?

### ISSUE THREAD

**Issue by tanzir71** [llazzaro/django-scheduler#331]
Installed Bower. Very confused by what is meant by components folder. No such folder in my project.

Also, I installed Django All Auth. I didn't configure the social network API's yet but when I go to log in, log out, signup page, "this is a demo of a calendar..." shows up. When I disable schedule, the log out, signup pages work.

**Comment by llazzaro** [comment]
@tanzir71 bower has nothing to do with this project check the documentation of django-bower at https://github.com/nvbn/django-bower.
I know this project uses bower, but it's up to you to use it.
Django scheduler is compatible with all auth, I think it sound like a urls.py issue.
Check that in the urls.py you have a regex that will not override the other urls.
Hope it helps

**Comment by llazzaro** [comment]
If you continue with the issues let me know and we reopen the issue, but we need a stack trace or more information.
Thanks!
