### ISSUE TITLE
Would it be possible to customize the sorting order of periods?

### ISSUE THREAD

**Issue by m-vdb** [llazzaro/django-scheduler#340]
Hi there,

Would it be possible to customize the sorting order of periods? It's "hard-coded" [here](https://github.com/llazzaro/django-scheduler/blob/develop/schedule/models/events.py#L670-L671) and I need to override it. Of couse I can still re-apply `sorted()` with a different sorting order after calling `period.get_occurrences()` but for performance reasons I think it would be better to make the `Occurrence` class customizable.

I can come up with a PR if this is something you're willing to include in your codebase 😄

**Comment by llazzaro** [comment]
What do you think of passing a function on the __init__ and if defined using it on __lt__?
Probably you though more the solution, if you have a better one let me know.

If you have the time I will ove a PR!  But remember to add unit tests!

**Comment by m-vdb** [comment]
ah yes that's a good idea, I'll do that

**Comment by llazzaro** [comment]
ok! If you don't have time I can code the unit tests.
