### ISSUE TITLE
Please submit 0.8.6 to pypi

### ISSUE THREAD

**Issue by lampslave** [llazzaro/django-scheduler#345]

**Comment by llazzaro** [comment]
Will do it this weekend. Do you need any particular fix? 
thanks for reporting this

**Comment by lampslave** [comment]
>Do you need any particular fix?

No, I just want to use last version :)

**Comment by jdufresne** [comment]
> Do you need any particular fix?

The added migration in commit https://github.com/llazzaro/django-scheduler/commit/3b260c886f1695f99dbfbc1d846e5966e5c36600 would be nice. 0.8.5 breaks on my CI server as it checks for no missing migrations.

**Comment by llazzaro** [comment]
done 
https://pypi.python.org/pypi/django-scheduler/0.8.6

sorry for delaying this.

**Comment by jdufresne** [comment]
Thanks @llazzaro!

Would you mind publishing a wheel package as well? If you're not familiar with wheels, when you'd normally run `python3 setup.py sdist upload`, run instead `python3 setup.py sdist bdist_wheel upload`.

For more information see http://pythonwheels.com/

The advantages of wheels are:

* Faster installation.
* Avoids arbitrary code execution for installation. (Avoids setup.py)
* Allows better caching for testing and continuous integration.
* Creates .pyc files as part of installation to ensure they match the python interpreter used.
* More consistent installs across platforms and machines.

**Comment by llazzaro** [comment]
@jdufresne Strange I tough I uploaded the wheel. thanks for let me know this, it was a mistake.

**Comment by llazzaro** [comment]
@jdufresne Uploaded 3.6.1 with your command instead of using twine. But I think 0.8.6 was uploaded using wheels.
I followed your steps and 0.8.6.1 was released (pipy don't let me to upload 0.8.6 again).
Let me know if the new version is ok, but I think is the same as 0.8.6

My steps for publishinh 0.8.6 were these:

python setup.py sdist bdist_wheel
twine upload dist/django-scheduler-0.8.6.tar.gz

python version used was 3.6.1

**Comment by jdufresne** [comment]
Hmm. I still don't see a wheel.

If you look at the release page, https://pypi.python.org/pypi/django-scheduler, there is no `.whl` file. If you compare to Django page, https://pypi.python.org/pypi/Django/1.11.5, which does have a `.whl` file.

Does the command `twine upload dist/django-scheduler-0.8.6.tar.gz` need to also include the built wheel? Something like `twine upload dist/django-scheduler-0.8.6.tar.gz dist/django-scheduler-0.8.6-py2.py3-none-any.whl`?

**Comment by llazzaro** [comment]
For some reason I didn't have the .whl in the dist directory. I just uploaded the file

**Comment by jdufresne** [comment]
Thanks!
