### ISSUE TITLE
Package broken on Django 2.0

### ISSUE THREAD

**Issue by pszalanski** [llazzaro/django-scheduler#364]
After an update to Django 2.0 I cannot use `manage.py`, because of the following error:

```
[...]\venv\lib\site-packages\schedule\models\calendars.py", line 6, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

The function `reverse` was actually moved to `django.urls`.

**Comment by llazzaro** [comment]
@jdufresne is working on a pull request.
https://github.com/llazzaro/django-scheduler/pull/350
I will try to release a new version soon.
Thanks!

**Comment by pszalanski** [comment]
Oh, sorry, I could have looked at the PRs first. Alright then, good to know.

Am 02.12.2017 19:48 schrieb "Leonardo Lazzaro" <notifications@github.com>:

**Comment by llazzaro** [comment]
There are some urls that are broken after django 2.0 update.
This is normal since all templates are missing namespace.

**Comment by jdufresne** [comment]
@llazzaro Thanks for the report. If you have steps to reproduce, I can try to see if I can get a fix.

Apologies if I've introduced a regression.

**Comment by llazzaro** [comment]
@jdufresne you didn't introduce a regression! some changes are required after upgrading to django 2.0 when using namespaces.
When using namespaces some url in templates are broken (this was reported in an old issue), however with the new django 2.0 we are forced to use namespaces in urls (I think).
Don't worry I will try to take a look to it tomorrow.
I wanted to know if you were using templates and if you could reproduce the error.
I will try to add some tests to reproduce this issue also.

**Comment by jdufresne** [comment]
@llazzaro What do you think about the change proposed in llazzaro/django-scheduler-sample#32? Or would you rather I universally apply the URL namespace across the entire library? I'm open to either approach.

**Comment by llazzaro** [comment]
I'm always in doubt about this. Just avoid changing all urls in the project for now.
I'm open to changing this in the future.
PR on sample was merged.

**Comment by woodz-** [comment]
@llazzaro: so you dont't like your django-scheduler is being reused? Please refer to my comment on #302.

**Comment by llazzaro** [comment]
@woodz- a lot of people are reusing the project. I'm open to the change, but I didn't have time to do it.
I think we should do this change, this project is very old and the good practices of reuse from django were not so common.
I will try to make some time to make the project more easy to be reused.
Thanks for the comment!
