### ISSUE TITLE
Next release (with Django 2.0 support)

### ISSUE THREAD

**Issue by jdufresne** [llazzaro/django-scheduler#381]
@llazzaro

I'd like to document what is required to make the next release happen. My projects are waiting on the Django 2.0 support. If there are any specific blocker tickets, let me know, I'm happy to help out and fix them.  Thanks for the django-scheduler!

**Comment by WakeRealityDev** [comment]
I'm trying to get it working with Django 2.0.1 and confuse.d  The demo app seems to say Django 2.0 is there, and was updated 29 days ago with references to Django 2.  However, it looks for a django-scheduler 0.8.7 that it can't find.

Refrence: https://github.com/llazzaro/django-scheduler-sample/blob/master/requirements.txt

**Comment by jdufresne** [comment]
@llazzaro I saw you updated the version number. You'll need to merge #386 before releasing, but please let CI tests pass before merging. Thanks!

**Comment by llazzaro** [comment]
0.8.7 with django 2.0 support was released.
Please let me know if you find any issues!
