### ISSUE TITLE
Devs: HowTo 'git clone' this project and edit on the python and run on Linux?

### ISSUE THREAD

**Issue by WakeRealityDev** [llazzaro/django-scheduler#400]
Hi.  I'm new to django and confused on how to download this project from a github checkout in a way that I can run and edit the python source directly from the project directory structure.

I'm on Ubuntu Linux 16.04. Here are the steps I'm following so far:

    git clone https://github.com/llazzaro/django-scheduler.git
    cd django-scheduler/
    virtualenv -p python3 env --no-site-packages
    source env/bin/activate
    nano requirements.txt
        change to use Django 2.0.1
    pip3 install -r requirements.txt
    nano secrets.sh
        export SECRET_KEY='new key'

I'm following this guide: https://stackoverflow.com/questions/37094032/how-to-run-cloned-django-project - and the next step in the guide is to run manage.py - but **I don't have a manage.py in my project tree**?

Can someone please help me work out specific steps for this particular project?  Thank you.

**Comment by llazzaro** [comment]
This is a django app and not a django project.
You need to first bootstrap a django app and then install the project using:

> python setup.py develop

using develop allows you to change the code

**Comment by WakeRealityDev** [comment]
I'm still a bit lost in details, because other projects I have found tend to have a test folder that contains manage.py... and I'm new to django structure understanding.  Here is another stab at the issue:

    mkdir zztemptry1
    cd zztemptry1
    mkvirtualenv django-scheduler
    workon django-scheduler
    git clone https://github.com/llazzaro/django-scheduler.git django-scheduler
    cd django-scheduler/
    nano requirements.txt 
   python3 setup.py develop --user
   pip3 install -r requirements.txt 
   git clone https://github.com/llazzaro/django-scheduler-sample.git
   python3 ./manage.py bower install
   python3 ./manage.py migrate
   python3 ./manage.py collectstatic
   python3 ./manage.py load_sample_data
   python3 ./manage.py load_example_data
   python3 ./manage.py runserver

What are devs doing on Linux?  Can you then edit the Python source files, and have them reflect the code changes/ Or do I need to re-run collectstatic command?  Or can you give some other tips of how to stay within the project source control structure for edit, run, test, edit cycle? Thank you.

**Comment by llazzaro** [comment]
this project need some tutorial see issue #97 for status
