### ISSUE TITLE
Status for specific occurrences

### ISSUE THREAD

**Issue by knasti** [llazzaro/django-scheduler#436]
I have a question regarding occurrences. In the Task class below, inherited from Event, I have some fields that are applicable for all occurrences of that specific Event/Task, such as priority and required skills, which works. But I would like for each occurrence in a given period to have a status e.g. "not assigned", "assigned", "ended", "canceled" and possibly more. Can anyone point me towards a solution to this problem? I found the "cancel_occurence" in the documentation that somewhat touches on this problem, but doesn't quite address "assigned" and "not assigned" statuses. 

```
from schedule.models import Event

class Task(Event):
    duration = models.DurationField()

    PRIORITY_CHOICES = ((1, _("High")), (2, _("Medium")), (3, _("Lav")))

    priority = models.IntegerField(choices=PRIORITY_CHOICES, null=True, default=PRIORITY_CHOICES[1][0], verbose_name=_('priority'))  # 1 high, 2 medium, 3 low

    STATUS_CHOICES = ((1, _('Not assigned')), (2, _('Assigned')), (3, _('Ended')), (4, _('Cancelled')))

    status = models.IntegerField(choices=STATUS_CHOICES, null=True, default=STATUS_CHOICES[0][0], verbose_name=_('status'))

    required_skills = models.ManyToManyField("miscellaneous.Skill", blank=True, verbose_name=_('required skills'))
    required_employees = models.ManyToManyField("employee.Employee", blank=True, verbose_name=_('required employees'))
    department = models.ForeignKey(
        "miscellaneous.Department", on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('department')
    )
    tasktype = models.ManyToManyField(TaskType, blank=True, verbose_name=_('task type'))
    customer = models.ManyToManyField("miscellaneous.Customer", blank=True, verbose_name=_('customer'))
```

I hope you can help.

**Comment by lggwettmann** [comment]
I solved this issue by using a model with a foreign key to Occurrence. You have to make sure in the YourModel.save() function that you persist the occurrence by saving it.

It's not a very elegant solution but I don't think subclassing Occurrence is possible at this point in time. Please correct me if I'm wrong.
