### ISSUE TITLE
DeprecationWarning The 'execute_manager' function is deprecated

### ISSUE THREAD

**Issue by llazzaro** [llazzaro/django-scheduler#44]
/home/travis/virtualenv/python2.6/lib/python2.6/site-packages/django/core/management/**init**.py:465: DeprecationWarning: The 'execute_manager' function is deprecated, you likely need to update your 'manage.py'; please see the Django 1.4 release notes (https://docs.djangoproject.com/en/dev/releases/1.4/).
  DeprecationWarning)

**Comment by jdufresne** [comment]
Was fixed in 96443d3fdcdba5124ae7fdfac4af8fa9cc5201c2
