### ISSUE TITLE
Duplicate migration

### ISSUE THREAD

**Issue by chrisspen** [llazzaro/django-scheduler#457]
There are two migrations with the conflicting number, 0008. This breaks Django's migrate command. Also, it looks like the `0008_calendar_slug_unique.py` migration may have been made in error since it throws an error, complaining that the unique index was created in a previous migration.

I had to delete the `0008_calendar_slug_unique.py` file to get the migrate command working again.

**Comment by llazzaro** [comment]
thanks for reporting this issue!
