### ISSUE TITLE
Version 0.9.2 is missing a git tab

### ISSUE THREAD

**Issue by jdufresne** [llazzaro/django-scheduler#459]
Hi @llazzaro 

I see a new version was released but a git tag is not in the repo. Would you mind adding a tag for the version you used?

I also see a Python 3 wheel is missing, could that be uploaded to PyPI as well?

I don't mind taking care of it, if you prefer. I just need to know the git hash is to follow through. Thanks!

**Comment by llazzaro** [comment]
Sorry about this.
I just uploaded the wheel and tagged the repo.

**Comment by jdufresne** [comment]
Thanks!
