### ISSUE TITLE
How to adapt it to create a slotbooking system?

### ISSUE THREAD

**Issue by losanki** [llazzaro/django-scheduler#467]
Hello, I am creating an app to book facilities which have different time slots per day(mostly 30 minutes long). Currently I have a slotbooking model and when a slotbooking is done I manually create an event in the facility calendar as well as the user calendar, but I feel there must be a better way to do it. Having slight difficulty in understanding the terminology. Any help is appreciated!

**Comment by llazzaro** [comment]
I think you need to use recurrent event every 30 min. You model should have a foreign key to the event and this means that the slot was reserved.
This is an initial idea and it could contain bug or issue, but I hope it helps you to kick start your problem
Hope it helps!

**Comment by losanki** [comment]
Thanks, but I am not sure I understand. An event every 30 min would be a one time event right? Or if it is an event which recurs every 30 min and suppose I create 12 occurrences but I can not use FK relation to individual occurrence. I find the fullcalendar with get_occurrences api really easy to use and that's the way I was intending to use it somehow.

**Comment by losanki** [comment]
I ended up using the event model as base for my slotbooking model and using fullcalendar's date and time input for slots instead of creating recurring event because in a sense it's implied in fullcalendar. Only now need to figure out validation to prevent overlapping events. Thanks, closing now!
