### ISSUE TITLE
unconverted data remains: +01:00

### ISSUE THREAD

**Issue by practiceryan** [llazzaro/django-scheduler#480]
Hi, 

Note: I'm using the fullcalendar.js as is in the sample project.

I'm calling the api/occurrences for events and its responding with:
"unconverted data remains: +01:00"

I've set both timezones (in settings.py and the fullcalendar.js) to Europe/London.
Is there something im missing?

**Comment by fraank** [comment]
The FullCalendar urls generated by [Moment-Plugin](https://fullcalendar.io/docs/moment-plugins) are in the wrong format:

    http://localhost:3000/shedule/api/occurrences?calendar_slug=calendar1&start=2020-05-31T00%3A00%3A00%2B02%3A00&end=2020-07-12T00%3A00%3A00

Correct would be sth. like:

    http://localhost:3000/shedule/api/occurrences?calendar_slug=calendar1&start=2020-05-31T00%3A00%3A00&end=2020-07-12T00%3A00%3A00&timeZone=Europe%2FAmsterdam

Try adding a timezone config param in FullCalendar-Config, like:

    timeZone: 'Europe/Amsterdam',

**Comment by practiceryan** [comment]
Thank you, i seem to have put the timeZone parameter in the events block.
