### ISSUE TITLE
FullCalendar API does not support ISO8601 date strings w/ UTC offset

### ISSUE THREAD

**Issue by josassy** [llazzaro/django-scheduler#489]
Hi there,

There hasn't been much activity on this project lately, so I don't know if this project is still maintained, but I thought I would give a try. 

From the [FullCalendar docs](https://fullcalendar.io/docs/events-json-feed), FullCalendar v5 currently requests for events using ISO8601 date strings that include a UTC offset, such as `2013-12-01T00:00:00-05:00`. When tested with django-scheduler, FullCalendar seems to throw a 400 error when using these datestrings.

According to my debugging efforts, the relevant code throwing the error is found in `_api_occurrences`:
```
# version 2 of full calendar
# TODO: improve this code with date util package
if "-" in start:

    def convert(ddatetime):
        if ddatetime:
            ddatetime = ddatetime.split(" ")[0]
            try:
                return datetime.datetime.strptime(ddatetime, "%Y-%m-%d")
            except ValueError:
                # try a different date string format first before failing
                return datetime.datetime.strptime(ddatetime, "%Y-%m-%dT%H:%M:%S")

else:

    def convert(ddatetime):
        return datetime.datetime.utcfromtimestamp(float(ddatetime))
```
The ValueError is being thrown when the ISO8601 string fails to be parsed by the "%Y-%m-%dT%H:%M:%S" format string. I see some notes about improving the code with the `dateutil` package. Looking at their docs, the method [parser.isoparse](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.isoparse) seems to be of interest, and might allow us to move away from manual datetime format strings.

It appears that there is some timezone logic following the above code. I wonder if that logic could be deprecated in favor of using that the ISO8601 string which already includes timezone information if desired.

Any thoughts on this? I may be able to contribute toward making this change, but it obviously depends on support from the maintainers.

**Comment by af2005** [comment]
As an easy fix, replace the above lines with
```python
def convert(ddatetime):
    return dateutil.parser.parse(ddatetime, ignoretz=True)
```

**Comment by josassy** [comment]
Yes, I ended up doing something similar with external code, then handing it to the API in the `%Y-%m-%d` format. Thanks for reminding me about this issue - I will go ahead and close since there is a simple workaround.
