### ISSUE TITLE
feature request: swappable Event model

### ISSUE THREAD

**Issue by smcoll** [llazzaro/django-scheduler#50]
i would like to be able to define my own Event model from an abstract event base model.  In this way, i could add several fields to my model without having to maintain a separate fork, as i presently do.  i know this is an undertaking, but this would have great benefit.  It would help keep the app focused on scheduling but allow users to customize their calendar experience.

**Comment by dekoza** [comment]
Subclassing `Event` as `MyEvent` is not an option in many cases. Consider this example:
Suppose I subclassed Event as MyEvent and Occurrence as MyOccurrence. In both models I added some fields and methods. Then let's say I have MyOccurrence instance. If I access its `event` attribute I am accessing Event instance, not MyEvent instance (as Occurrence defines field `event = ForeignKey(Event)`). This way I cannot access my additional fields and methods defined on MyEvent directly - I need to fetch MyEvent from the db based on the Event I already have - which makes another db hit and therefore is far from being optimal.

**Comment by llazzaro** [comment]
in your case plase check the answer here, I think we need to add more fields to suport that case http://stackoverflow.com/questions/2949674/django-inheritance-with-foreignkey-field

**Comment by dekoza** [comment]
I'm making some improvements on the lib for a project. I'll post some pull-requests after I'm done.

**Comment by smcoll** [comment]
We could implement something like Django handles the swappable User model: have a `EVENT_MODEL` setting referring to the class (defaults to Event) and also a method for returning that class like `get_event_class()` which could be leveraged from time to time.  The FK on Occurrence could be written like `event = ForeignKey(settings.EVENT_MODEL)`.

@dekoza  Curious; have you found a use case for a custom Occurrence model, or was that just for illustration?

**Comment by jdufresne** [comment]
Done in #110
