### ISSUE TITLE
Cancelled recurring event occurrences still showing in FullCalendar

### ISSUE THREAD

**Issue by ataylor32** [llazzaro/django-scheduler#508]
Based on issue #378, I understand that django-scheduler is intended to be used with FullCalendar. I have a problem I'm running into when using the `api_occurrences` view.

Suppose I usually have a meeting every Monday, so I create a recurring event for that meeting. But sometimes that meeting has to occur on Tuesday instead of Monday due to holidays. I can get that to work with FullCalendar just fine like this:

```python
Occurrence.objects.create(
    event=weekly_meeting_event,
    start=weekly_meeting_event.start.replace(year=2021, month=6, day=1),
    end=weekly_meeting_event.end.replace(year=2021, month=6, day=1),
    original_start=weekly_meeting_event.start.replace(year=2021, month=5, day=31),
    original_end=weekly_meeting_event.end.replace(year=2021, month=5, day=31),
)
```

But let's say there's a week where I'm going to skip the meeting completely (instead of moving it to a different day), so I want to delete it. I tried doing it like this:

```python
Occurrence.objects.create(
    event=weekly_meeting_event,
    start=weekly_meeting_event.start.replace(year=2021, month=12, day=27),
    end=weekly_meeting_event.end.replace(year=2021, month=12, day=27),
    cancelled=True,
    original_start=weekly_meeting_event.start.replace(year=2021, month=12, day=27),
    original_end=weekly_meeting_event.end.replace(year=2021, month=12, day=27),
)
```

In this scenario, the JSON returned by the `api_occurrences` view indicates that the event has been cancelled, but this has no effect on FullCalendar; FullCalendar still displays the event. Do I have FullCalendar misconfigured or is this a bug with django-scheduler? Maybe this is documented somewhere and I'm missing it?

**Comment by llazzaro** [comment]
Thanks for reporting this bug!

I added a filter to cancelled occurrences. 
This was released with version 0.9.4
