### ISSUE TITLE
Headless Integration

### ISSUE THREAD

**Issue by RobSisson** [llazzaro/django-scheduler#545]
Hi; love the project, some super nice stuff in here!

Just wondering how you'd recommend using this in a headless manner as I'd like to build a front end using HTMX.

My thinking is that I could copy the models/views/forms etc and put them into my own project, where I can edit them as required, rather than installing it via pip. 

Is this strategy something you'd recommend, or do you have any other suggestions?

Thanks again for making this awesome package and sharing it with us!

Cheers, Rob

**Comment by llazzaro** [comment]
Hi!

You should do as any other python library, install the dependency with pip and import the models.
copy things to a vendor directory should be avoided.
