### ISSUE TITLE
Missing static files

### ISSUE THREAD

**Issue by kwando1313** [llazzaro/django-scheduler#70]
Where are the static files? It seems that when I plug in the app there is no 'static' folder to get the images such as 'add.png'

**Comment by rcooke** [comment]
I'm also trying to get a feel for this project using your default urls and views.

But they are calling for missing static CSS and JS files - JqueryUI static bits and even icon images.  

I tried importing the stuff in the sample project, but there are a bunch of images being called for that do not exist in the sample project.  (schedule/css/image/ui-bg_glass_20.....png  (very long file names)

Also some templates have hard-coded to load CSS and JS from an "asset" folder.  Or media in some cases.

Is there a plan to provide a clean sample program or app?

Or, is there a sample project someplace I can use to learn the APIs?

**Comment by llazzaro** [comment]
Ok, I will add again the static files.
My idea was to use bower, but this will increase the learning curve of the project

**Comment by llazzaro** [comment]
please read the new instruction at Readme or here http://django-bower.readthedocs.org/en/latest/installation.html

after adding djangobower to your settings, execute python mange.py bower install and it will install bootstrap and jquery.

scheduler base template will generate static jQuery.js and bootstrap.css urls to use djangobower files.
