### ISSUE TITLE
feed link is broken in template (thus resulting in 404)

### ISSUE THREAD

**Issue by teolemon** [llazzaro/django-scheduler#82]
In the sample templates, in the calendar view, there is a list of links
All of them adapt well automatically to the custom url structure I've chosen excepted the "Feed" link.
Example:
http://127.0.0.1:8000/calendar/calendar/daily/admin1s-calendar/
http://127.0.0.1:8000/schedule/feed/calendar/upcoming/1/
The culprit seems to be line 23.
https://github.com/llazzaro/django-scheduler/blob/f70daf45643ca9334456a85bc9455d516507b068/schedule/templates/schedule/calendar.html
(and yes, it's not the most clever one ever, it's just a test)

**Comment by llazzaro** [comment]
I review this. I added a test and updated the template to use reverse for urls.
However, please check that your settings.py has the right settings for SITE_ID and yout Site model is correclty populated since django feed requires it,
