### ISSUE TITLE
Fresh install: Can't migrate/syncdb ? 

### ISSUE THREAD

**Issue by syndbg** [llazzaro/django-scheduler#83]
I pip installed and added `schedule` in INSTALLED_APPS.

However when trying to run syncdb/migrate I get:

```
CommandError: One or more models did not validate:
schedule.eventrelation: Accessor for field 'content_type' clashes with related field 'ContentType.eventrelation_set'. Add a related_name argument to the definition for 'content_type'.
```

If I have to guess, I'm probably missing some app to add or it's just not working?

P.S I'm using Django 1.6.5

**Comment by llazzaro** [comment]
please use pip install django-scheduler==0.7.3

upgrade to django 1.8 if you can!
